image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - chmod +x gradlew
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info
